### ISSUE TITLE
Images get zoomed

### ISSUE THREAD

**Issue by Snow344** [dnet/pySSTV#18]
<img src=https://i.imgur.com/zjxCIXm.jpg>

**Comment by dnet** [comment]
If you mean that the top left _x_ by _y_ rectangle of the image is used where _x_ is the width, _y_ is the height of the selected mode, it's by design. I guess one could put resize/resample functionality into the command line version, but then you need options for the user to

 - select the algorithm to resize/resample (fast vs. nice choices) and more importantly,
 - choose how to handle aspect ratio issues.

For latter, one could argue that

 - stretching is great because there are modes with non-square pixels (Martin M2 and Scottie S2 are two such examples), and on the other hand
 - keeping the aspect ratio is great because it makes sense for modes with square pixels.

Even keeping the aspect ratio is non-trivial, since if the ratio of the width and height of the image doesn't match that of the mode (typically 4:3), you can either

 - fill the image and cut off from the sides or top + bottom or
 - use the whole image and fill the empty sides or top + bottom with _something_ (also known as letterboxing and pillarboxing).

Since there is no one true answer to these questions, it'd only seem logical to add options for all these, which could be done in the command line interface. What do you think?

**Comment by dnet** [comment]
I uploaded v0.4.1 to PyPI, which already contains this feature.
